export const TEST_POSTGRESQL_CHANNEL = 'TEST_POSTGRESQL_CHANNEL'
export const TEST_POSTGRESQL_SUCCESS_CHANNEL = 'TEST_POSTGRESQL_SUCCESS_CHANNEL'
export const TEST_POSTGRESQL_REJECT_CHANNEL = 'TEST_POSTGRESQL_REJECT_CHANNEL'
