export const PostgreSQLChannels = {
  testConnection: {
    name: 'TEST_POSTGRESQL_CHANNEL',
    success: 'TEST_POSTGRESQL_CHANNEL_SUCCESS',
    reject: 'TEST_POSTGRESQL_CHANNEL_REJECT'
  },
  getDatabases: {
    name: 'GET_POSTGRESQL_DATABASES_CHANNEL',
    success: 'GET_POSTGRESQL_DATABASES_CHANNEL_SUCCESS',
    reject: 'GET_POSTGRESQL_DATABASES_CHANNEL_REJECT'
  },
  getSchemas: {
    name: 'GET_POSTGRESQL_SCHEMAS_CHANNEL',
    success: 'GET_POSTGRESQL_SCHEMAS_CHANNEL_SUCCESS',
    reject: 'GET_POSTGRESQL_SCHEMAS_CHANNEL_REJECT'
  },
  getSchemaTables: {
    name: 'GET_POSTGRESQL_SCHEMA_TABLES_CHANNEL',
    success: 'GET_POSTGRESQL_SCHEMA_TABLES_CHANNEL_SUCCESS',
    reject: 'GET_POSTGRESQL_SCHEMA_TABLES_CHANNEL_REJECT'
  },
  getTableColumns: {
    name: 'GET_POSTGRESQL_TABLE_COLUMNS_CHANNEL',
    success: 'GET_POSTGRESQL_TABLE_COLUMNS_CHANNEL_SUCCESS',
    reject: 'GET_POSTGRESQL_TABLE_COLUMNS_CHANNEL_REJECT'
  },
  getViews: {
    name: 'GET_POSTGRESQL_VIEWS_CHANNEL',
    success: 'GET_POSTGRESQL_VIEWS_CHANNEL_SUCCESS',
    reject: 'GET_POSTGRESQL_VIEWS_CHANNEL_REJECT'
  }
}
